use std::collections::BTreeSet;
use std::path::Path;

use ci_lang::Column;

/// Rewrite the "Idioms by source" section of ATTRIBUTIONS.md from the
/// reg-rs tests in reg/: every idiom that has a test, under its source.
pub fn write_attributions(root: &Path) -> Result<usize, String> {
    let ids = tested_idioms(&root.join("reg"))?;
    let path = root.join("ATTRIBUTIONS.md");
    let text = std::fs::read_to_string(&path).map_err(|e| e.to_string())?;
    let head = text
        .find("## Idioms by source")
        .map(|i| &text[..i])
        .ok_or("ATTRIBUTIONS.md has no \"## Idioms by source\" section")?;
    let list: String = ids.iter().map(|i| format!("- {i}\n")).collect();
    let body = format!(
        "## Idioms by source\n\nGenerated by `compare-idioms attributions` from the reg-rs tests in\n\
         `reg/`. Do not edit by hand. Ids are this project's.\n\n\
         ### X_eTaL Rosetta data ({})\n\n{list}",
        ids.len()
    );
    std::fs::write(&path, format!("{head}{body}")).map_err(|e| e.to_string())?;
    Ok(ids.len())
}

/// Idiom ids from test names `idiom-<id>-<column>.rgt`.
fn tested_idioms(reg: &Path) -> Result<BTreeSet<String>, String> {
    let entries = std::fs::read_dir(reg).map_err(|e| format!("{}: {e}", reg.display()))?;
    Ok(entries
        .filter_map(|e| e.ok()?.file_name().into_string().ok())
        .filter_map(|n| idiom_of(&n))
        .collect())
}

fn idiom_of(file: &str) -> Option<String> {
    let rest = file.strip_prefix("idiom-")?.strip_suffix(".rgt")?;
    Column::ALL
        .iter()
        .find_map(|c| rest.strip_suffix(&format!("-{}", c.name())))
        .map(str::to_string)
}
